@startuml overview

class Connect4
'connect4 main classes:'
class Player
class Turn
class Board
class Token

class Square

'goals'
abstract class Goal
class InRow
class InDiagonal
class InColumn
class InInverseDiagonal

'events'
class TokenPlaced

'token & player color'
enum Color{
red
yellow
}

'connect4 composites'
Connect4 *-down-> "2" Player
Connect4 *-down-> Turn
Connect4 *-down-> Board

'turn dependencies'
Turn -right-> Player

'player dependencies'
Player -right-> Board
Player -down-> Goal
Player -down-> Color
Player -down-> "6x7/2" Token

'board dependencies'
Board *-down-> "6*7" Square

'token placed event dependencies'
TokenPlaced -right->  Token
TokenPlaced -right-> Square : target

'goal dependencies'
Goal .down.-> "4..6x7/2" TokenPlaced

'square dependencies'
Square o-down-> "0..1" Token

'goal children'
Goal <|-down- InRow
Goal <|-down- InColumn
Goal <|-down- InDiagonal
Goal <|-down- InInverseDiagonal

'token dependencies'
Token -down-> Color

@enduml