@startuml analysis

class Connect4 {

    + initConnect4()
    + play()
}
Connect4 ..> Game
Connect4 *--> YesNoDialog
Connect4 ..> EnumSetup

class Game {     

    + initGame()
    + play()
}
Game *--> Turn
Game *--> Board
Game *--> "2" Player
Game ..> Color

class Turn {

    + initTurn(players)
    + change()
    + getActive() : Player        
}
Turn --> "2" Player

class Player {

    + initPlayer(board, color)
    + placeToken()
    + showWin();
    + getColor() : Color
}
Player --> Board
Player --> Color
Player *--> LimitedIntDialog

class Board {
    - ROWS = 6
    - COLUMNS = 7
    
    + initBoard(numPlayers)
    + isColumnFull(column)
    + getColumnsLenght()
    + placeToken(column, color)
    + isConnect4(color)
    + isFull()
    + show()
}
Board ..> ClosedInterval
Board *--> "2 x 0..6x7/2" Coordinate : playersCoordinates
Board ..> Direction
Board ..> Color

class Coordinate {
    + initCoordinate(row, column)
    + isInColumn(column)
    + getRow()
    + getColumn()
    + shift(direction, forward)
}
Coordinate ..> Direction

enum Direction {
    VERTICAL
    HORIZONTAL
    DIAGONAL
    INVERSE_DIAGONAL

    + {static} values()
    + shiftRow(row, forward)
    + shiftColumn(column, forward)
}

enum Color {
    + X
    + O   
    + NONE 

    + {static} get(ordinal) : Color  
    + {static} values()  
    + ordinal()
    + isNone()
    + toString()
}

class YesNoDialog #LightGreen {  
    - question
    - answer   
    - YES
    - NO

    + initYesNoDialog(question)
    + ask()
    + isAffirmative()
}

class LimitedIntDialog #LightGreen {
    - requested
    - prefix
    

    + initLimitedIntDialog(requested, prefix, max, min = 1) 
    + ask()
}
LimitedIntDialog *--> ClosedInterval : limits

class ClosedInterval {
    - max
    - min

    + initClosedInterval(max, min)
    + includes(value)
    + toString()
}

class EnumSetup {
    setUp()
}
EnumSetup ..> Color
EnumSetup ..> Direction

@enduml