@startuml analysis

class Connect4 {

    + initConnect4()
    + play()
}
Connect4 *--> YesNoDialog
Connect4 ..> Game

class Game {     

    + initGame()
    + play()
}
Game *--> Turn
Game *--> Board

class Turn {
    - turnValue

    + initTurn(numPlayers, board)    
    + change()      
    + playerPlaceToken()        
    + isPlayerWinner()
    + showPlayerWin()
}
Turn *--> "numPlayers" Color : playersColors
Turn *--> LimitedIntDialog : columnDialog
Turn --> Board

class Board {
    - ROWS = 6
    - COLUMNS = 7
    
    + initBoard(numPlayers)
    + isColumnFull(column)
    + placeToken(column, color)
    + isWinner(color)
    + show()
    + getColumnsCount()
}
Board *--> "0..ROWS x COLUMNS" Coordinate : playersPlaceds
Board ..> ClosedInterval
Board ..> Direction
Board ..> Color

class Coordinate {
    - row
    - column 

    + initCoordinate(row, column)
    + shift(rowShift, columnShift)
    + equals(other)   
    + hasRowInInterval(interval)
    + hasColumnInInterval(interval)
}
Coordinate ..> ClosedInterval

class ClosedInterval {
    - max
    - min

    + initClosedInterval(max, min = 0)
    + includes(value)
    + toString()
}

enum Direction {
    VERTICAL
    HORIZONTAL
    DIAGONAL
    INVERSE_DIAGONAL

    - initDirection(rowShift, columnShift)
    + {static} values()
    + shift(coordinate, forward)
}
Direction ..> Coordinate

enum Color {
    + X
    + O   
    + NONE 

    - initColor(value)
    + {static} get(ordinal) 
    + {static} values()  
    + ordinal()
    + isNone()
    + toString()
}

class YesNoDialog #LightGreen {  
    - question
    - answer   
    - YES
    - NO

    + initYesNoDialog(question)
    + ask()
    + isAffirmative()
}

class LimitedIntDialog #LightGreen {
    - requested
    - prefix
    
    + initLimitedIntDialog(requested, max, min = 1, prefix = "") 
    + ask()
    + setPrefix(prefix)
}
LimitedIntDialog *--> ClosedInterval : limits

@enduml